services:
  postgres:
    image: postgres:latest
    container_name: clior-dev-db
    restart: always
    environment:
      POSTGRES_DB: clior-dev-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
